//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizComputation.Model.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Answers
    {
        public int Answer_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Quiz_id { get; set; }
        public Nullable<int> Question_id { get; set; }
        public Nullable<int> Selected_Option_id { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual Options Options { get; set; }
        public virtual Questions Questions { get; set; }
        public virtual Quizzes Quizzes { get; set; }
        public virtual Users Users { get; set; }
    }
}
